-
  name: 'RBAC for Kubelet Authorization'
  hosts: master-1
  tasks:
    -
      name: 'Create system:kube-apiserver-to-kubelet ClusterRole to access Kubelet API'
      shell: |
        cd /vagrant/.vagrant/shared-folder
        cat <<EOF | kubectl apply --kubeconfig admin.kubeconfig -f -
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRole
        metadata:
          annotations:
            rbac.authorization.kubernetes.io/autoupdate: "true"
          labels:
            kubernetes.io/bootstrapping: rbac-defaults
          name: system:kube-apiserver-to-kubelet
        rules:
          - apiGroups:
              - ""
            resources:
              - nodes/proxy
              - nodes/stats
              - nodes/log
              - nodes/spec
              - nodes/metrics
            verbs:
              - "*"
        EOF
    -
      name: 'Bind the system:kube-apiserver-to-kubelet ClusterRole to the system:kube-apiserver user'
      shell: |
        cd /vagrant/.vagrant/shared-folder
        cat <<EOF | kubectl apply --kubeconfig admin.kubeconfig -f -
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRoleBinding
        metadata:
          name: system:kube-apiserver
          namespace: ""
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:kube-apiserver-to-kubelet
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: kube-apiserver
        EOF
